// ============================================================
// RoboCore-1 Hardware PID Controller
// 8 independent PID loops for motor position control
// Runs at 1MHz update rate — no CPU involvement
// Part of the RoboCore-1 robotics SoC
// Open Source — MIT License
// ============================================================

module pid_controller #(
    parameter NUM_CHANNELS  = 8,     // 8 PID loops (one per 2 PWM channels)
    parameter POS_WIDTH     = 32,    // position data width from encoder
    parameter GAIN_WIDTH    = 16,    // width of Kp, Ki, Kd gain registers
    parameter OUT_WIDTH     = 16,    // output width matches PWM duty cycle
    parameter ACC_WIDTH     = 48     // accumulator width — prevents overflow
)(
    // Clock and reset
    input  wire                         clk,
    input  wire                         rst_n,

    // 1MHz tick — PID updates on this pulse
    // Generated by dividing 100MHz clock by 100
    input  wire                         tick_1mhz,

    // Target positions — set by CPU
    input  wire [POS_WIDTH-1:0]         target  [0:NUM_CHANNELS-1],

    // Actual positions — from encoder interface
    input  wire [POS_WIDTH-1:0]         actual  [0:NUM_CHANNELS-1],

    // Gain registers — set by CPU at startup
    input  wire [GAIN_WIDTH-1:0]        kp      [0:NUM_CHANNELS-1],
    input  wire [GAIN_WIDTH-1:0]        ki      [0:NUM_CHANNELS-1],
    input  wire [GAIN_WIDTH-1:0]        kd      [0:NUM_CHANNELS-1],

    // Output limit — clamp output to this value
    input  wire [OUT_WIDTH-1:0]         out_max [0:NUM_CHANNELS-1],

    // Enable per channel
    input  wire [NUM_CHANNELS-1:0]      enable,

    // Anti-windup limit for integrator
    input  wire [ACC_WIDTH-1:0]         int_limit [0:NUM_CHANNELS-1],

    // PID output — connect to PWM engine duty cycle
    output reg  [OUT_WIDTH-1:0]         pid_out [0:NUM_CHANNELS-1],

    // Status
    output reg  [NUM_CHANNELS-1:0]      at_target,   // 1 when position error < threshold
    output reg  [NUM_CHANNELS-1:0]      saturated    // 1 when output is clamped
);

// ============================================================
// Internal registers
// ============================================================

// Error terms
reg signed [POS_WIDTH:0]    error       [0:NUM_CHANNELS-1];
reg signed [POS_WIDTH:0]    error_prev  [0:NUM_CHANNELS-1];

// PID terms — wide enough to prevent overflow
reg signed [ACC_WIDTH-1:0]  p_term      [0:NUM_CHANNELS-1];
reg signed [ACC_WIDTH-1:0]  i_term      [0:NUM_CHANNELS-1];
reg signed [ACC_WIDTH-1:0]  d_term      [0:NUM_CHANNELS-1];
reg signed [ACC_WIDTH-1:0]  integrator  [0:NUM_CHANNELS-1];
reg signed [ACC_WIDTH-1:0]  pid_sum     [0:NUM_CHANNELS-1];

// At-target threshold — within 10 counts = close enough
localparam AT_TARGET_THRESHOLD = 10;

// ============================================================
// PID update — runs on every 1MHz tick
// Sequential channel update — one channel per clock after tick
// All 8 channels updated within 8 cycles = still effectively 1MHz
// ============================================================

integer j;
reg [3:0] ch_idx;   // current channel being updated
reg       updating; // currently in update sequence

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        ch_idx   <= 0;
        updating <= 0;

        for (j = 0; j < NUM_CHANNELS; j = j + 1) begin
            error[j]      <= 0;
            error_prev[j] <= 0;
            p_term[j]     <= 0;
            i_term[j]     <= 0;
            d_term[j]     <= 0;
            integrator[j] <= 0;
            pid_sum[j]    <= 0;
            pid_out[j]    <= 0;
            at_target[j]  <= 0;
            saturated[j]  <= 0;
        end
    end else begin

        // Start update sequence on 1MHz tick
        if (tick_1mhz) begin
            updating <= 1;
            ch_idx   <= 0;
        end

        // Process one channel per clock cycle
        if (updating) begin

            if (enable[ch_idx]) begin

                // Step 1 — Calculate error
                error[ch_idx] <= $signed(target[ch_idx])
                                - $signed(actual[ch_idx]);

                // Step 2 — Proportional term
                p_term[ch_idx] <= $signed(kp[ch_idx])
                                * $signed(error[ch_idx]);

                // Step 3 — Integral term with anti-windup
                // Only accumulate if not saturated
                if (!saturated[ch_idx]) begin
                    integrator[ch_idx] <= integrator[ch_idx]
                                        + $signed(error[ch_idx]);
                end

                // Clamp integrator to prevent windup
                if (integrator[ch_idx] > $signed(int_limit[ch_idx]))
                    integrator[ch_idx] <= $signed(int_limit[ch_idx]);
                else if (integrator[ch_idx] < -$signed(int_limit[ch_idx]))
                    integrator[ch_idx] <= -$signed(int_limit[ch_idx]);

                i_term[ch_idx] <= $signed(ki[ch_idx])
                                * integrator[ch_idx];

                // Step 4 — Derivative term
                d_term[ch_idx] <= $signed(kd[ch_idx])
                                * ($signed(error[ch_idx])
                                 - $signed(error_prev[ch_idx]));

                // Step 5 — Sum all terms
                pid_sum[ch_idx] <= p_term[ch_idx]
                                 + i_term[ch_idx]
                                 + d_term[ch_idx];

                // Step 6 — Clamp output to valid PWM range
                if (pid_sum[ch_idx] < 0) begin
                    // Negative output — motor drives backward
                    // For now clamp to zero (unidirectional mode)
                    pid_out[ch_idx]  <= 0;
                    saturated[ch_idx] <= 1;
                end else if (pid_sum[ch_idx] > out_max[ch_idx]) begin
                    pid_out[ch_idx]  <= out_max[ch_idx];
                    saturated[ch_idx] <= 1;
                end else begin
                    pid_out[ch_idx]  <= pid_sum[ch_idx][OUT_WIDTH-1:0];
                    saturated[ch_idx] <= 0;
                end

                // Step 7 — At target check
                if (error[ch_idx] < AT_TARGET_THRESHOLD &&
                    error[ch_idx] > -AT_TARGET_THRESHOLD)
                    at_target[ch_idx] <= 1;
                else
                    at_target[ch_idx] <= 0;

                // Step 8 — Store previous error for derivative
                error_prev[ch_idx] <= error[ch_idx];

            end else begin
                // Disabled channel — zero output, clear state
                pid_out[ch_idx]    <= 0;
                integrator[ch_idx] <= 0;
                at_target[ch_idx]  <= 0;
                saturated[ch_idx]  <= 0;
            end

            // Advance to next channel or finish
            if (ch_idx == NUM_CHANNELS - 1) begin
                updating <= 0;
                ch_idx   <= 0;
            end else begin
                ch_idx <= ch_idx + 1;
            end

        end
    end
end

endmodule